name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        required: true
        description: "labhousemobile/audioapp-cog-whisper-diarization"
        default: "labhousemobile/audioapp-cog-whisper-diarization"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
          cog-version: "v0.16.8"

      - name: Inject HF Token into predict.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Use sed to find and replace the placeholder
          # -i = in-place edit
          # "..." = use double quotes to allow $HF_TOKEN shell variable expansion
          # s|...|...|g = substitute, using | as a delimiter (safer than /)
          sed -i "s|HF_AUTH_TOKEN|$HF_TOKEN|g" predict.py
      
      - name: Push to Replicate
        run: |
          cog push r8.im/${{ inputs.model_name }}

